### ISSUE TITLE
Visibility of Activity Log (13 + 3 est.)

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#121]
**As a user involved in an event I want the activity log to be only visible to other involved users so that other users cannot interfere with the organization.**

See glossary for a definition of involved users.

**Acceptance Criteria:**
- [ ] Activity log is neither transimitted nor shown for a user that is not involved

**Comment by leoselig** [comment]
Is visible to all users -> not accepted

**Comment by mweisz** [comment]
Please have a look at #272.

**Comment by leoselig** [comment]
@mweisz 
This is already implemented, reviewed and merged into the dev - including integration of comments

**Comment by leoselig** [comment]
@kaozente @olegsfinest
Just reviewd -> Looks good
Please create PR, final review after merge in dev, as always
