### ISSUE TITLE
User Interface (Menu)

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#138]
**As a user I want to work with a user friendly and clear menu in order to navigate more quickly to each site.**

- [ ] there should be the following Menu points
   - [ ] Dashboard
   - [ ] Task
   - [ ] Administration
   - [ ] Approval / Open Requests / My Requests

**Comment by mweisz** [comment]
Everything besides Properties should already be implemented (#174). Properties are included in our (Axolotl) 4th sprint (#273 ).
