### ISSUE TITLE
Search for a room in Room view [est. cost: 8]

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#151]
**As a user I want to filter the list of rooms in order to better find the rooms I look for.**

- [x] the list of rooms can be filtered by name and size
- [x] name filter field provides auto-completion

![untitled](https://cloud.githubusercontent.com/assets/5164846/5328354/6e22dfd0-7d79-11e4-916d-fae01dc9ae68.png)

**Comment by hagerapante** [comment]
auto-completion is given through the instant result view
