### ISSUE TITLE
User profile [8]

### ISSUE THREAD

**Issue by LeoKotschenreuther** [hpi-swt2/event-und-raumplanung#154]
**As a user I want to edit my Profile in order to give other people the possibility to contact me.**

I can reach the profile if I click on my name that is displayed on top of the page

The profile should contain the following points:
- [x] Real name
- [x] Phone numbers
 - [x] Office
 - [x] Mobile
- [x] Office location
- [x] Turn on and off Email notifications
- [x] Switch UI Language between English and German with a dropdown
- [x] Save Button

![screen shot 2014-12-17 at 10 16 18](https://cloud.githubusercontent.com/assets/6781162/5468938/d403d0ca-85d5-11e4-9245-1a21614131d4.png)

**Comment by LeoKotschenreuther** [comment]
Update: Added missing attribute about language (switch between german and english)

**Comment by jaSunny** [comment]
Sprache und rechtschreibung bearbeiten
