### ISSUE TITLE
Update profile on first login [6]

### ISSUE THREAD

**Issue by LeoKotschenreuther** [hpi-swt2/event-und-raumplanung#190]
**As a user I want to update my profile directly after my first login.**

- [x] Display a view directly after the first login where the user can fill in the following information:
 - [x] Real Name
 - [x] Office location (building and room)
 - [x] Mobile phone
 - [x] Office phone
 - [x] Switch language with a dropdown (german and english)
- [ ] Fetch Given Name and Family Name, Work and Mobile Telephone number if set from openID
- [ ] Prefill in the fields you did fetch from openID (given and family Name in one field)

Remarks:
- [x] All information is optional
- [x] The user can either skip all or fill in some data
- [x] Direct the user in both cases afterwards to his dashboard

![screen shot 2014-12-14 at 18 08 20](https://cloud.githubusercontent.com/assets/6781162/5428264/8b3a0262-83bc-11e4-930c-5cae10b087d0.png)

**Comment by LeoKotschenreuther** [comment]
Update: Fetch attributes from openID and fill them in first

**Comment by LeoKotschenreuther** [comment]
Update: Added missing attribute about language (switch between german and english)

**Comment by jaSunny** [comment]
"NotificatioN" wrong geschrieben; translation

**Comment by jaSunny** [comment]
@LeoKotschenreuther is the spelling mistake fixed?
