### ISSUE TITLE
Login with foreign user address

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#205]
When one is authenticated with openid and now one is logging in with another email address in the event-raumplanungstool, the system grants me access with the wrong credentials. Seems to be that a permission check is missing

**Comment by leoselig** [comment]
This should get resolved by #217

**Comment by jaSunny** [comment]
okay cool then lets close it

**Comment by leoselig** [comment]
I think we should reopen it as an indication until it actually gets resolved

**Comment by jaSunny** [comment]
maybe refers to #210

**Comment by leoselig** [comment]
Fixed after #217
