### ISSUE TITLE
[Bug] Sessions change to different user

### ISSUE THREAD

**Issue by Atyanar** [hpi-swt2/event-und-raumplanung#210]
With some action the current user changes, so that you are logged in as a different user than you initially logged in as (most probably switching the id's of the two users AND saving that to the database, as an old session cookie logs me in as another user who definitely never was using my pc).

![image](https://cloud.githubusercontent.com/assets/6772156/5627693/4adee948-959c-11e4-8e7c-17c4b2213ab7.png)

**Comment by Atyanar** [comment]
However, I am unable to replicate this error...

**Comment by leoselig** [comment]
Fixed with #217
