### ISSUE TITLE
room flag (intern, extern)

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#216]
**As housekeeping I want to be also able to manage external rooms (like one from the University of Potsdam) in order to improve the usability of the system**

- [x] create a flag for rooms for external locations
- [x] add this flag for room filtering option in event creation

**Comment by jaSunny** [comment]
maybe also an issue of permission management

**Comment by jaSunny** [comment]
In consultation with @leoselig we can solve that via room properties :)

**Comment by jaSunny** [comment]
In consultation with @leoselig we can solve that via room properties :)

**Comment by philipp94831** [comment]
@jaSunny so nothing to do here? I already did it by the way ;)

**Comment by jaSunny** [comment]
:+1:

**Comment by LeoKotschenreuther** [comment]
We decided to use room properties for external rooms
