### ISSUE TITLE
[Improvement] import of openID Information and editing of those

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#218]
**As system I want to automatically import Profile informations from openID and give the user the change to edit them in order to improve the usability**

- [ ] import all possible openID Profile informations
- [ ] give a user the chance to edit his profile data after first import
- [ ] let the user generally edit his profile informations (?)

**Comment by LeoKotschenreuther** [comment]
Looks like duplicate of #190
@jaSunny correct me if i'm wrong

**Comment by jaSunny** [comment]
you are right!
