### ISSUE TITLE
activity log rejection  of events [3SP] 

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#235]
**As an Event owner I want to see a rejection of the related events in the activity log to improve the understanding of the userflow**

- [ ] include a notification of a rejection in the related event activity log

**Comment by jaSunny** [comment]
[3SP] low

**Comment by github1992** [comment]
Seems to be already implemented:
![image](https://cloud.githubusercontent.com/assets/7300387/5979768/e3e7060e-a8aa-11e4-846d-33a26967e133.png)

**Comment by github1992** [comment]
@jaSunny Do you agree that the feature is already fully implemented?

**Comment by jaSunny** [comment]
@github1992  i can confirm that.  Another group was overzealous :-) . thanks for the check . :+1:
