### ISSUE TITLE
[Improvement] Only be able to approve an event if you are responsible for all rooms in the request

### ISSUE THREAD

**Issue by r-springer** [hpi-swt2/event-und-raumplanung#236]

**Comment by jaSunny** [comment]
@LeoKotschenreuther isnt that a topic of permission management?

**Comment by LeoKotschenreuther** [comment]
Yes, you are right

**Comment by jaSunny** [comment]
**As a system I want only user to approve an event if he is responsible for all rooms in the request in order to improve security**
