### ISSUE TITLE
Make it easier to see that you can select multiple rooms on event creation

### ISSUE THREAD

**Issue by r-springer** [hpi-swt2/event-und-raumplanung#237]
**As a user who creates an Event I want to be able to understand quickly that I am able to filter more than one room**

**Comment by jaSunny** [comment]
refers to #257

**Comment by jaSunny** [comment]
@mweisz is maybe also?

**Comment by jaSunny** [comment]
prio high

**Comment by r-springer** [comment]
included in #257
