### ISSUE TITLE
Print room time table [est. cost: 4 + 6 + 20 = 30]

### ISSUE THREAD

**Issue by r-springer** [hpi-swt2/event-und-raumplanung#239]
**As a user I want to print a time table for a room in order to put it up at the room so others can see what events are in there.**

- [x] Link in administration dropdown-menu
- [ ] Link from room details page (room preselected then)

There should be a new 'create time tables' page. On the page there should be:
- [ ] A multiselect like the one shown in the image (two boxes between which you can move the rooms, one of them includes the selected rooms)
    - This is for selecting for which rooms time tables should be printed
![multiselect example](https://cloud.githubusercontent.com/assets/5947468/5799718/e5cdf2b2-9fd5-11e4-9a63-84004f222d58.png)
- [x] Links/Buttons to "select all" and "deselect all"
- [x] A select box to choose the week the time tables should be printed for.
- [x] A button "Generate time table(s)" which leads to the next page. On this page the generated time tables for all selected rooms should be displayed in a way that you can print them from the browser.
    - [x] when printed one page contains one time table

The time table itself should be as similar as possible to the current time tables used at HPI.
- [x] A time table shows the events of one week (Monday - Sunday).
- [x] Every scheduled event is shown as a box from its start point to its end point
- [x] For public events, show the name.
- [x] For private events, don't show any details. Just show a placeholder message "Room blocked".

**Comment by jaSunny** [comment]
prio high
