### ISSUE TITLE
Group Creation and Group Editing should have the same layout

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#250]
**As a user who creates a group I want to have the same fields / options as when I edit a group**

- [ ] link both to the same layout.
- [ ] when editing, fill with related default values..

**Comment by LeoKotschenreuther** [comment]
Update: As one page for creation and editing doesn't work out, we will leave the create page like it is and redirect after the creation to the edit page.
@philipp94831
