### ISSUE TITLE
Properties are missing in Room Editing Page

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#252]
**As a user I want to be able to edit propertise also in room editing page in order to improve the userflow**

**Comment by jaSunny** [comment]
@mweisz status here?

**Comment by mweisz** [comment]
@jaSunny Good question. Leo K should know more about it - I merely reported the bug. :-)
@LeoKotschenreuther ?

**Comment by LeoKotschenreuther** [comment]
We have an extra page for that (see /room_properties)

**Comment by mweisz** [comment]
Alright, then we can close this issue, I guess.
