### ISSUE TITLE
Date Picker for Task Due Date (8 est.)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#254]
**As a user that is creating a new task I want to select the due date by using a date picker so that I do not have to manually type a well-formatted date.**

**Acceptance Criteria:**
- [ ] Date picker works cross-browser (Chrome/Firefox) i.e. does not rely on a native type="date" picker

**Comment by jaSunny** [comment]
refers to #44

**Comment by leoselig** [comment]
Reviewed in branch, ready to merge into dev

**Comment by leoselig** [comment]
Date picker opens but does not put date into field when clicking on a day
Moved back to "in progress"
Please revert changes in dev
