### ISSUE TITLE
[CRITICAL][Improvement] room filtering view [est. cost: 10]

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#257]
**As a user I want to clearly understand the  room filtering "module" in the event creation in order to improve the user flow**

point out the room filtering section and improve the overall look of the mask
- [x] put the rooms select and the filtering in a box so the user can see they belong together
- [x] change the rooms select from a single line select to a multiline select or a multiselect with two boxes (as shown in the mockup)
    - to satisfy #237 
    - alternatively: display a message: "You can select multiple rooms at once. Selected rooms are 
- [x] fix #200 (together with team Elch)

![room filtering](https://cloud.githubusercontent.com/assets/5947468/5800956/8e61127e-9fe5-11e4-92de-de09b5c04eab.png)

**Comment by jaSunny** [comment]
@mweisz could you include that in your sprint?

**Comment by jaSunny** [comment]
prio high

**Comment by mweisz** [comment]
@jaSunny Sorry, our sprint is already full. But it seems as René will take care of this. :-)

**Comment by jaSunny** [comment]
:+1: awesome!

**Comment by jaSunny** [comment]
please be aware that #200 #64 are fixed
