### ISSUE TITLE
[10] Eventpage UI Tweaks (13 est.)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#263]
**As a user I want the event view page to display all relevant information regarding a certain event in a neatly arranged and uncluttered way.**

This includes the following changes:
- [x] If the event takes place on multiple days, the time span should be visible both in the upper right-hand corner (*start_date* - *end_date*) and below the title of the event (*start_time*, *start_date* - *end_time*, *end_date*
- [x] The description box should not include redundant information and therefore only display *Event Creator*, *Number of Attendees*, *Last Update*, and (only visible for the event creator) the event's *status*  
- [x] The description text should be floating around the info box
- [x] The margin above and below the description text should be equal
- [x] The entire task section should not be visible if the person is not involved in the event (i.e. neither the creator nor assigned to a certain task)

---
##### Conceptual Mockup
*Used only for illustrating the concept, __not__ the actual design.*

![bildschirmfoto 2015-01-16 um 00 30 11](https://cloud.githubusercontent.com/assets/1974386/5769106/4e1d9226-9d17-11e4-8b79-8430c1c753c4.png)

**Comment by rosabraatz** [comment]
Soll der Eintrag Wiederholungsmuster in der Tabelle bleiben? Wenn ja, an welche Position?
