### ISSUE TITLE
return button at page for assigning rooms to groups

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#265]
**As a user I want to be able to redirect back from the assignment-of-rooms-to-groups view by using a button within the website in order to improve UX**

- [x] add a back button the the assignment-of-rooms-to-groups page which redirects back

there is no return button at this page
**http://event-und-raumplanung-dev.herokuapp.com/groups/1/manage_rooms**

![untitled](https://cloud.githubusercontent.com/assets/5164846/5749663/48629ca4-9c4b-11e4-91e6-842b8b32470f.png)

**Comment by jaSunny** [comment]
@mweisz

**Comment by mweisz** [comment]
@jaSunny Sorry, our sprint is already full. Needs to be done by another group.

**Comment by jaSunny** [comment]
- [ ] add return button for this page
