### ISSUE TITLE
error page when visiting "Veranstaltungen"

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#266]
error page when visiting "Veranstaltungen"
**http://event-und-raumplanung-dev.herokuapp.com/events**
![untitled](https://cloud.githubusercontent.com/assets/5164846/5749693/a71af3ae-9c4b-11e4-8c62-9358aa5d584e.png)

**Comment by jaSunny** [comment]
maybe a DB reset is necessary again

**Comment by jonaskeutel** [comment]
should be fixed

**Comment by jaSunny** [comment]
thanks!
