### ISSUE TITLE
[15] Remove Accomplished Tasks from Widget (2h est.)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#274]
**As a user that accepted a task assignment, I want that specific task to be removed from the 'My Tasks' widget on the dashboard as soon as I mark that task as done. This way I can easily tell what still needs to be done.**

- [x] As soon as a task is marked as done (either form within the dashboard or directly on the event's page) the task is removed from the widget
- [x] The task remains listed in the list on the event's page

---

##### Conceptual Mockup
*Used only for illustrating the concept, __not__ the actual design.*

![bildschirmfoto 2015-01-16 um 05 02 01](https://cloud.githubusercontent.com/assets/1974386/5771432/30ce946a-9d3d-11e4-8eab-8afbc44c84af.png)

**Comment by jaSunny** [comment]
duplicates #186
