### ISSUE TITLE
[CRITICAL] Remove Obsolete Global Task List

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#283]
**As a user I do not want to be able to view a global list of all the task in the system as this completely undermines task security and visibility on the according event pages.**

- [ ] The */tasks* page should be removed from the system and not be accessible anymore

---

##### Conceptual Mockup
*Used only for illustrating the concept, __not__ the actual design.*

![bildschirmfoto 2015-01-18 um 14 12 51](https://cloud.githubusercontent.com/assets/1974386/5792511/1ac78d26-9f1c-11e4-93e1-2a273631d79d.png)

**Comment by jaSunny** [comment]
der Zurück button von event detail view führt auf die task liste

**Comment by mweisz** [comment]
@jaSunny: Ja, du hast Recht. Das wird sich aber mit diesem Sprint endlich ändern, sodass man direkt auf die zugehörige Eventseite kommt.

**Comment by jaSunny** [comment]
:+1:

**Comment by LeoKotschenreuther** [comment]
Duplicates #158
