### ISSUE TITLE
Link to Occurance from Calender

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#284]
**As a user I want an entry for a repeating event in thecalender to link to the occurance page rather than the whole series so that I can see the specific details of that occurance.**

**Acceptance Criteria:**
- [ ] All occurences are listed in the calendar
- [ ] Clicking on the entry links to the specific occurance (similar to #199)

**Comment by leoselig** [comment]
@LeoKotschenreuther
As discussed, this should definately be done at the end of the sprint

**Comment by mweisz** [comment]
:+1:

**Comment by leoselig** [comment]
@LeoKotschenreuther 
What is the state of this story?? This is absolutely necessary to make repeating events usable
As far as I understand, the current implementation ignored the information my team gave your developers so that implementing this requires at least a small refactoring of your code...
@stephde @Atyanar @SvenLehmann @numberpi @Somae
