### ISSUE TITLE
Event filter checkbox doesn't always show correct state [est. cost: 1]

### ISSUE THREAD

**Issue by r-springer** [hpi-swt2/event-und-raumplanung#290]
When I select the my events only filter on the event list page, go to another page (dashboard e.g.) and then come back to the event list, the content seems to be cached/remembered (only my events are shown) but the checkbox doesn't indicate that.
-> It should also be checked then.
![bildschirmfoto 2015-01-19 um 10 25 27](https://cloud.githubusercontent.com/assets/5947468/5799666/531e4606-9fd5-11e4-82bd-4fd79053de64.png)

**Comment by hagerapante** [comment]
already fixed

**Comment by hagerapante** [comment]
@r-springer
could you check fix?

**Comment by r-springer** [comment]
works, great!
