### ISSUE TITLE
[annoying] Tests (and Travis build successes) should be independet of their start time/date

### ISSUE THREAD

**Issue by Somae** [hpi-swt2/event-und-raumplanung#299]
Travis Builds fail only because they are started before midnight and some tests are executed after midnight
Build server also seems to have diffrent results for DateTime.now and Date.today, maybe consistent use fixes some issues with that test.

lulufaber (cant assign you, git blame said it's your test):
  1) rooms/details.html.erb must not show both events, only the first
     Failure/Error: room.bookings.first.start.to_date.should == Date.today
       expected: Mon, 19 Jan 2015
            got: Tue, 20 Jan 2015 (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -Mon, 19 Jan 2015
       +Tue, 20 Jan 2015
       
     # ./spec/views/rooms/details.html.erb_spec.rb:51:in `block (2 levels) in <top (required)>'

**Comment by mweisz** [comment]
:+1: for the annoying tag!. :-)

**Comment by jaSunny** [comment]
@Somae can you confirm that this issue is fixed?

**Comment by github1992** [comment]
Travis fails before commit:
https://travis-ci.org/hpi-swt2/event-und-raumplanung/builds/47983383
Travis passes after commit:
https://travis-ci.org/hpi-swt2/event-und-raumplanung/builds/47990381
The Travis builds were run between 0 and 1 o'clock.

**Comment by jaSunny** [comment]
okay thanks!
