### ISSUE TITLE
Activity Log Entry for failed Task Creation

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#304]
**Reproduction:**
- create event
- try to create task for event that has some validation error (e.g. no name)
- go back to event page
- task is not created (correct) but activity log entry has been created

**Comment by leoselig** [comment]
@Thulur 
@mr-flannery

**Comment by mr-flannery** [comment]
Probably affects updating as well. We'll look into it.

**Comment by mr-flannery** [comment]
@leoselig I think this one has been in the dev for a week or so.... review time! Yay.
