### ISSUE TITLE
[SHOWSTOPPER] Heroku Dev "Application Error"

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#311]
Some commit of this day seems to have created a major application error that occurs on any route at http://event-und-raumplanung-dev.herokuapp.com/

This error is not logged on errbit
We traced it down to be an issue **after** the commit 0943c86 and **before** the commit 3e466c9
To anyone with a commit in this range: @ArneMayer @hsgfan @hagerapante 
Please revisit your created revisiions on your local machine and revert or fix **as soon as possible**
The sooner you do that the earlier you are off the hook... ;)

Nochmal die Scrum Master, der Form halber: @Atyanar @lulufaber @rosabraatz @DasDingGehtNicht @SvenLehmann

**Comment by hagerapante** [comment]
I don't see any errors. Is it solved or is there another problem? Could you elaborate the problem?

**Comment by ArneMayer** [comment]
I don't get any errors either.

**Comment by leoselig** [comment]
What the Heck?
So we all got that error, even after re-running Travis
no commit since then...

**Comment by leoselig** [comment]
Has this ever happened before?

**Comment by Atyanar** [comment]
Sorry, my fault. I forgot resetting the dev to the faulty state. There it is again.

**Comment by leoselig** [comment]
Okay, so the problem persists
Please review your changes

**Comment by hubx** [comment]
passiert so früh, dass errbit nicht getriggert wird. hier die `heroku logs`. Weil ich immer noch sehr wenige hier contributors im Heroku sehe, hier die logs
> 2015-01-24T12:36:11.634937+00:00 heroku[web.1]: State changed from crashed to starting
> 2015-01-24T12:36:20.009424+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 13699 -e production`
> 2015-01-24T12:36:24.579271+00:00 app[web.1]: => Rails 4.1.6 application starting in production on http://0.0.0.0:13699
> 2015-01-24T12:36:24.723645+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:465:in `each'
> 2015-01-24T12:36:24.723664+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
> 2015-01-24T12:36:24.723684+00:00 app[web.1]: 	from /app/config.ru:3:in `block in <main>'
> 2015-01-24T12:36:24.723707+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/server.rb:50:in `app'
> 2015-01-24T12:36:24.579250+00:00 app[web.1]: => Booting WEBrick
> 2015-01-24T12:36:24.723647+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:465:in `eager_load!'
> 2015-01-24T12:36:24.723666+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
> 2015-01-24T12:36:24.723686+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
> 2015-01-24T12:36:24.723708+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
> 2015-01-24T12:36:24.579273+00:00 app[web.1]: => Run `rails server -h` for more startup options
> 2015-01-24T12:36:24.723648+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:346:in `eager_load!'
> 2015-01-24T12:36:24.723670+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
> 2015-01-24T12:36:24.723690+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
> 2015-01-24T12:36:24.723712+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
> 2015-01-24T12:36:24.579275+00:00 app[web.1]: => Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
> 2015-01-24T12:36:24.723652+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/application/finisher.rb:58:in `each'
> 2015-01-24T12:36:24.723671+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
> 2015-01-24T12:36:24.723691+00:00 app[web.1]: 	from /app/config.ru:in `new'
> 2015-01-24T12:36:24.723713+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/server.rb:69:in `start'
> 2015-01-24T12:36:24.579278+00:00 app[web.1]: Exiting
> 2015-01-24T12:36:24.723656+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
> 2015-01-24T12:36:24.723675+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
> 2015-01-24T12:36:24.723696+00:00 app[web.1]: 	from /app/vendor/bundl
> e/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
> 2015-01-24T12:36:24.723720+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:76:in `tap'
> 2015-01-24T12:36:24.579276+00:00 app[web.1]: => Ctrl-C to shutdown server
> 2015-01-24T12:36:24.723654+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
> 2015-01-24T12:36:24.723673+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
> 2015-01-24T12:36:24.723692+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
> 2015-01-24T12:36:24.723717+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:81:in `block in server'
> 2015-01-24T12:36:24.723639+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
> 2015-01-24T12:36:24.723659+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
> 2015-01-24T12:36:24.723678+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
> 2015-01-24T12:36:24.723699+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
> 2015-01-24T12:36:24.723725+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
**> 2015-01-24T12:36:24.723633+00:00 app[web.1]: /app/app/controllers/ical_controller.rb:1:in `<top (required)>': uninitialized constant AppilcationController (NameError)**
> 2015-01-24T12:36:24.723657+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
> 2015-01-24T12:36:24.723676+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
> 2015-01-24T12:36:24.723697+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
> 2015-01-24T12:36:24.723722+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:76:in `server'
> 2015-01-24T12:36:24.723641+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:467:in `each'
> 2015-01-24T12:36:24.723661+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
> 2015-01-24T12:36:24.723681+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/application.rb:300:in `initialize!'
> 2015-01-24T12:36:24.723702+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
> 2015-01-24T12:36:24.723729+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
> 2015-01-24T12:36:24.723643+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:467:in `block in eager_load!'
> 2015-01-24T12:36:24.723662+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
> 2015-01-24T12:36:24.723683+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<top (required)>'
> 2015-01-24T12:36:24.723704+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
> 2015-01-24T12:36:24.723730+00:00 app[web.1]: 	from bin/rails:8:in `require'
> 2015-01-24T12:36:24.723734+00:00 app[web.1]: 	from bin/rails:8:in `<main>'
> 2015-01-24T12:36:25.677542+00:00 heroku[web.1]: State changed from starting to crashed
> 2015-01-24T12:36:25.671530+00:00 heroku[web.1]: Process exited with status 1
> 2015-01-24T14:47:09.092350+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=event-und-raumplanung-dev.herokuapp.com request_id=xx fwd="xx" dyno= connect= service= status=503 bytes=
>

**Comment by hubx** [comment]
Wie kann denn sowas durch die Tests durchgehen... es gibt nur Tests für 6/22 Controllern :(?

**Comment by r-springer** [comment]
I pushed a fix for this directly to the dev. Please have a look at it @DasDingGehtNicht and also be aware in the other teams. @Atyanar @lulufaber @rosabraatz  @SvenLehmann

**Comment by leoselig** [comment]
Seems to be fixed, but we have a nice follow-up issue #312
