### ISSUE TITLE
Calendar integration in other systems (OWA, phone...) [est. cost: 5]

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#33]
**As a user I want to be able to display my (approved and booked) rooms and events in my native calendar in order to integrate it with my current tools.**

via the Dashboard 

- [x] in the calendar part on the dashboard there should be a message that tells the user he can synchronize the calendar using a link that is displayed together with that message
- [x] the synchronization should work with (ics/iCal) format
- [x] the synchronized calendar should include all events that
    - [x] are owned by the user
    - [x] are favorited by the user
    - [x] have at least one task that is assigned to the user (or a group the user is member of)
- [x] it should really synchronize the calendar, not only import events once
- [x] the link should not be publicly accessible (authentication should be required to synchronize the calendar)

est. cost sprint 3: 30

**Comment by leoselig** [comment]
@r-springer 
Are repeating events in any way considerered for this?

**Comment by DasDingGehtNicht** [comment]
@leoselig 
yes they are
