### ISSUE TITLE
[CRITICAL] [bug] available filters cant be empty 

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#333]
delete Gemfile.lock.
execute bundle install.
now run rake db:setup

![pasted_image_at_2015_01_31_05_59_pm](https://cloud.githubusercontent.com/assets/5164846/5989792/5514e132-a993-11e4-9da8-7ed8fee0510f.png)
![pasted_image_at_2015_01_31_06_07_pm_360](https://cloud.githubusercontent.com/assets/5164846/5989793/55162556-a993-11e4-82e2-8ac45908f65f.png)

Weitere infos:

* Es gab ein update von  1.4.2 (hatten wir vorher) auf 2.4.3 (haben wir jetzt)
* mit der version 1.4.2  funktioniert der seed zwar, aber 61 Tests schlagen fehl.
* mit  2.4.3 kommt der besagte fehler

@Atyanar was able to reproduce it

**Comment by jaSunny** [comment]
@hagerapante does that make sense to you?

**Comment by hagerapante** [comment]
filterific api changed :-(
So gem version has to be < version 2

**Comment by hagerapante** [comment]
NameError: uninitialized constant I18n
I get this failure after deleting gem file and bundle install
anyone else?

**Comment by jaSunny** [comment]
@leoselig

**Comment by jaSunny** [comment]
so now its working again .. awkward
