### ISSUE TITLE
[critical] HPI-Image and RoomMate don't link to dashboard!

### ISSUE THREAD

**Issue by LeoKotschenreuther** [hpi-swt2/event-und-raumplanung#343]

**Comment by rosabraatz** [comment]
Kann ich leider nicht reproduzieren. Lädt zwar ewig, aber verlinkt immer noch auf das Dashboard.

**Comment by LeoKotschenreuther** [comment]
Ja, du hast Recht
Hatte wohl nicht die Geduld darauf 10s zu warten ;)
