### ISSUE TITLE
Cancel Alternative dialog delines event

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#347]

**Comment by kaozente** [comment]
Tatsächlich ist das Event schon declined in der Sekunde in der man auf das rote X in der Liste drückt, sprich wenn das Popup aufgeht ist das Event schon declined. Der Ablehnen Button im Popup hat also keine Funktion, man kann das Popup auch mit dem kleinen X schliessen und das Event bleibt trotzdem abgehlehnt...

**Comment by kaozente** [comment]
Man kann sich jetzt überlegen ob man das Popup einfach umlabelt, a la "Event ist jetzt abgelehnt, _zusätzlich_ eine Alternative vorschlagen?"
