### ISSUE TITLE
Influence of Acceptance test settings on unitTest

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#355]
config.action_controller.allow_forgery_protection must be true in order to work with sessions for the acceptance tests. But i causes that ~60 unitTest fails.

Currently config.action_controller.allow_forgery_protection = false so we should either 
* enable it for all acceptance tests or
* disable it for all non acceptance tests

this could be done with by using the acceptance test flag:

```
config.around(:each, :acceptance_test => true) do |ex|
```

relates to the Conversation on the commit:
https://github.com/hpi-swt2/event-und-raumplanung/commit/222a1c693ed7b6d5080d0f072f1fcdd84e73e9ca#commitcomment-9564748

**Comment by jaSunny** [comment]
okay, so setting config in spec_helper doesnt work out.
I now created a new environment which is executed after the test environment. That works fine, but now travis isnt loading the seeds file correctly... :/

**Comment by jaSunny** [comment]
juhuuuuuuuuu!
https://travis-ci.org/hpi-swt2/event-und-raumplanung/builds/49436435
ready to merge :)

**Comment by DasDingGehtNicht** [comment]
werent there 16 tests? i mean i had 9 tests passing too ;)

**Comment by jaSunny** [comment]
yea but they were excluded => true due to the point that they point to current user stories in Sprint 4 :)
