### ISSUE TITLE
extend Event creation with multiple rooms  [3 Storypoints] [6 Std]

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#64]
**As a user I want to be able to include multiple rooms in the booking request of an event in order to handle bigger amounts of event participants.**

- [ ] there should be an "add more rooms" button
- [ ] if add another room, i want to be able to filter again
- [ ] let the user delete already selected rooms from the filter (e.g. if one selected the wrong via filtering)

![integrate filtering in creation of events - v2](https://cloud.githubusercontent.com/assets/5164846/5057926/b043a6f6-6cda-11e4-9611-d788555eefa3.png)

**Comment by github1992** [comment]
i'm currently trying to fix it

**Comment by jaSunny** [comment]
cool. please be aware of #200

**Comment by github1992** [comment]
i'm actually trying to fix it #200

**Comment by jaSunny** [comment]
Vorabgenommen, bitte mergen
