### ISSUE TITLE
CRUD Comments (est. 14 hours)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#94]
**As a user I want to be able create, read, update, and delete [Comments](https://github.com/hpi-swt2/event-und-raumplanung/wiki/Glossar#comment)** .

- [x] A comment consists of an author ([user](https://github.com/hpi-swt2/event-und-raumplanung/wiki/Glossar#user)) , an actual content, a reference to a belonging [task](https://github.com/hpi-swt2/event-und-raumplanung/wiki/Glossar#task) and (at least) a creation timestamp 
- [x] The content of a message is limited to 500 characters (including spaces)
- [x] The author and the actual content of a comment are displayed
- [x] The comments should be rendered in a 'comment section' (i.e. some kind of box or panel)
- [x] The comments should appear in order of their creation (newest comment at the bottom)
- [x] Delete your own comments

---

##### Remarks and Prospect
Comments will be part of a commenting mechanism used inside events to enable (very basic) means of communicating and asking questions about tasks (see conceptual mockup below). 

The comments should belong to events and should be displayed in the event detail view!

![screen shot 2014-12-01 at 19 37 41](https://cloud.githubusercontent.com/assets/6781162/5250953/afaaaf6e-7991-11e4-9ecd-cecd14d58a46.png)

**Comment by leoselig** [comment]
I just reviewed #120 and accepted the story
@Thulur and @mr-flannery merged your work into their activity log, looks great, good job of you all! :)
Please talk to them prior to further implementation about merging and stuff

**Comment by jaSunny** [comment]
"Event wurde erfolgreich gelöscht" bitte beheben der Alert nachricht

**Comment by mr-flannery** [comment]
@jaSunny entweder ich verstehe deinen Kommentar falsch oder bei dir kommt nen Fehler, der bei mir nicht kommt.
